---
version: '3.4'

volumes:
  oracle-volume:

services:
  db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    expose:
      - "1521"
    environment:
      ORACLE_PASSWORD: oracle
    healthcheck:
      test: [ "CMD", "/checkDBStatus.sh"]
      interval: 10s
      retries: 60
      start_period: 30s
    volumes:
      - oracle-volume:/opt/oracle/oradata